name: Check PR and Commit

on:
  pull_request:
    paths:
      - 'operator/**'
    branches:
      - master

jobs:
  check-pr-and-commit:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.head.ref == 'release-please--branches--master--components--operator' && 
      contains(github.event.pull_request.title, 'chore( operator): community release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract PR Semver
        id: pr_semver
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          SEMVER=$(echo "$PR_TITLE" | sed -n 's/^chore( operator): community release \([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')
          echo "::set-output name=semver::$SEMVER"

      - name: Check Master Commits for Matching Semver
        id: check_commit
        run: |
          set +e
          MATCHING_COMMIT=$(git log --oneline master | grep -m 1 "chore(operator): prepare community release v${{ steps.pr_semver.outputs.semver }}")
          set -e
          if [ -n "$MATCHING_COMMIT" ]; then
            echo "Matching commit found: $MATCHING_COMMIT"
            echo "::set-output name=found::true"
          else
            echo "No matching commit found."
            echo "::set-output name=found::false"
          fi

      - name: Fail if No Matching Commit Found
        if: steps.check_commit.outputs.found == 'false'
        run: |
          echo "No matching commit found for the PR version ${{ steps.pr_semver.outputs.semver }}"
          exit 1
