name: operator-release-please

on:
  push:
    paths:
      - 'operator/**'
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: operator
          config-file: operator/release-please-config.json
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
      - name: "publish release"
        if: ${{ steps.release.outputs.releases_created }}
        with:
          release_created: ${{ steps.release.outputs.releases_created }}
          release_name: ${{ steps.release.outputs.tag_name }} 
        run: |
          gh release edit ${{ release_name }} --draft=false --latest=false