name: operator-release-please

on:
  push:
    paths:
      - 'operator/**'
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  releasePlease:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }} # e.g. v1.0.0
      version: ${{ steps.release.outputs.version }} # e.g. 1.0.0
      all: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: operator
          config-file: operator/release-please-config.json
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
  publishRelease:
    needs:
    - "releasePlease"
    runs-on: ubuntu-latest
    steps:
      - name: "check if release exists"
        id: "check_release"
        run: |
          echo "Release Created: " ${{ needs.releasePlease.outputs.all.releases_created }} 
          echo "Release Name: " ${{ needs.releasePlease.outputs.all.operator--name }} 
      - name: "publish release"
        if: ${{ needs.releasePlease.outputs.all.releases_created }}
        run: |
          gh release edit ${{ needs.releasePlease.outputs.all.operator--name }} --draft=false --latest=false