name: operator-release-please

on:
  push:
    paths:
      - 'operator/**'
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          path: operator
          config-file: operator/release-please-config.json
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
  publish-release:
    needs:
    - "release-please"
      runs-on: ubuntu-latest
      - name: "publish release"
        if: "${{ !fromJSON(needs.release-please.outputs.exists) || (needs.release-please.outputs.draft && fromJSON(needs.release-please.outputs.draft)) }}"
        run: |
          gh release edit ${{ needs.release-please.outputs.tag_name }} --draft=false --latest=false