name: operator-release-please

on:
  push:
    paths:
      - 'operator/**'
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  releasePlease:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.operator--release_created }}
      release_name: ${{ steps.release.outputs.operator--name }}
      all: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: operator
          config-file: operator/release-please-config.json
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
  publishRelease:
    needs:
    - "releasePlease"
    runs-on: ubuntu-latest
    steps:
      - name: "pull code to release"
        uses: "actions/checkout@v4"
        with:
          path: "release"
      - name: "check if release exists"
        env:
          GH_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        id: "check_release"
        run: |
          echo "Release Created: " ${{ needs.releasePlease.outputs.release_created }}
          echo "Release Name: " ${{ needs.releasePlease.outputs.release_name }}
          echo "Releases:"
          gh release list 
      - name: "publish release"
        env:
          GH_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        working-directory: "release"
        if: ${{ needs.releasePlease.outputs.release_created }}
        run: |
          gh release edit "${{ needs.releasePlease.outputs.release_name }}" --draft=false --latest=false