name: operator-release-please

on:
  push:
    paths:
      - 'operator/**'
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  releasePlease:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          path: operator
          config-file: operator/release-please-config.json
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
  publishRelease:
    needs:
    - "releasePlease"
    runs-on: ubuntu-latest
    steps:
      - name: "publish release"
        if: ${{ needs.releasePlease.outputs.release_created }}
        run: |
          gh release edit ${{ needs.releasePlease.outputs.tag_name }} --draft=false --latest=false