name: 'workflow'
on:
  push:
    branches:
      - master

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add OpenShift Supported versions to redhat catalog
        env:
          VERSION: 0.6.0
          OCP_SUPPORTED_VERSIONS: 'v4.12'
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "operators/loki-operator/0.6.0/metadata/annotations.yaml"
          propertyPath: "annotations.test"
          value: ${OCP_SUPPORTED_VERSIONS}
