name: 'workflow'
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set redhat-openshift-ecosystem specific variables
        env:
          version: 0.6.0
          ocpSupportedVersions: 'v4.12'
        run: |
          echo "ocpSupportedVersions=${ocpSupportedVersions}" >> $GITHUB_ENV
          echo version=${version} >> $GITHUB_ENV # update GitHub ENV vars

      - uses: actions/checkout@v3
      - name: Add OpenShift Supported versions to redhat catalog
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "operators/loki-operator/${{ env.version }}/metadata/annotations.yaml"
          propertyPath: "annotations['com.redhat.openshift.versions']"
          message: "add redhat community specifc annotation"
          commitChange: true
          createPR: false
          value: ${{ env.ocpSupportedVersions }}
