name: 'workflow'
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set redhat-openshift-ecosystem specific variables
        env:
          version: 0.6.0
          ocpSupportedVersions: 'v4.13'
        run: |
          echo "ocpSupportedVersions=${ocpSupportedVersions}" >> $GITHUB_ENV
          echo version=${version} >> $GITHUB_ENV # update GitHub ENV vars

      - uses: actions/checkout@v3
      - name: Add OpenShift Supported versions to redhat catalog
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "operators/loki-operator/${{ env.version }}/metadata/annotations.yaml"
          propertyPath: "annotations['com.redhat.openshift.versions']"
          message: "add redhat community specifc annotation"
          commitChange: false
          createPR: false
          value: ${{ env.ocpSupportedVersions }}

      - name: Use CLA approved github bot
        run: |
          git config user.name JoaoBraveCoding
          git config user.email 10974558+JoaoBraveCoding@users.noreply.github.com


      - name: Create pull request against JoaoBraveCoding/test-release
        env:
          VERSION: ${{ env.version }}
        run: |
          message="Update the loki-operator to $VERSION"
          body="Release loki-operator \`$VERSION\`.

          "
          branch="update-loki-operator-to-${VERSION}"

          # gh pr create doesn't have a way to explicitly specify different head and base
          # repositories currently, but it will implicitly pick up the head from a different
          # repository if you set up a tracking branch

          git checkout -b $branch
          git add -A
          git commit -s -m "$message"
          git push -f --set-upstream origin $branch
          gh pr create --title "$message" \
                       --body "$body" \
                       --repo JoaoBraveCoding/test-release \
                       --base main
