name: 'workflow'
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add OpenShift Supported versions to redhat catalog
        env:
          VERSION: 0.6.0
          OCP_SUPPORTED_VERSIONS: 'v4.12'
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "operators/loki-operator/0.6.0/metadata/annotations.yaml"
          propertyPath: "annotations['com.redhat.openshift.versions']"
          message: "add redhat community specifc annotation"
          commitChange: true
          createPR: false
          value: ${OCP_SUPPORTED_VERSIONS}
